### ISSUE TITLE
User 'root:root' is not supported

### ISSUE THREAD

**Issue by pPanda-beta** [synchrone/gcsfuse#2]
https://github.com/synchrone/gcsfuse/blob/e740420debd5d7a76616200f509c45124ce0e51b/Dockerfile#L13

You can not replace root with 'fuse' :( 

I tried running with 

```yaml
          env:
            - name: UID
              value: 0
            - name: GID
              value: 0
...
          securityContext:
            privileged: true
            runAsUser: 0
            runAsGroup: 0
            capabilities:
              add:
                - SYS_ADMIN

```

It didn't work
